version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    labels:
      - "traefik.enable=false"
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=db_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - traefik
  moodle:
    build: .
    labels:
            - "traefik.enable=true"
            - "traefik.backend=moodle"
            - "traefik.backend.healthcheck.path=/"
            - "traefik.backend.healthcheck.interval=1s"            
            - "traefik.frontend.rule=Host:localhost"
            - "traefik.frontend.headers.forceSTSHeader=true"
            - "traefik.frontend.headers.STSSeconds=315360000"
            - "traefik.frontend.headers.STSIncludeSubdomains=true"
            - "traefik.frontend.headers.STSPreload=true"
            - "traefik.port=80"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=db_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80'
      - '443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - traefik
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

networks:
   traefik:
       external:
           name: traefik_webgateway
